export type RateLimitScope =
  | "DRAFT_GENERATE"
  | "DRAFT_VERIFY"
  | "DRAFT_EDIT"
  | "REPLY_POST"
  | "BULK_APPROVE"
  | "GOOGLE_SYNC_LOCATIONS"
  | "GOOGLE_SYNC_REVIEWS"
  | "LOCATIONS_SELECT"
  | "SETTINGS_UPDATE"
  | "TEAM_INVITE"
  | "TEAM_INVITE_REVOKE"

export const RATE_LIMITS_PER_MINUTE: Record<RateLimitScope, number> = {
  DRAFT_GENERATE: 10,
  DRAFT_VERIFY: 30,
  DRAFT_EDIT: 20,
  REPLY_POST: 5,
  BULK_APPROVE: 2,
  GOOGLE_SYNC_LOCATIONS: 2,
  GOOGLE_SYNC_REVIEWS: 2,
  LOCATIONS_SELECT: 5,
  SETTINGS_UPDATE: 10,
  TEAM_INVITE: 5,
  TEAM_INVITE_REVOKE: 5,
}

export const AI_DAILY_BUDGET_PER_ORG = 200
export const POST_DAILY_BUDGET_PER_ORG = 200

export const COOLDOWN_MS = {
  GENERATE_DRAFT_REVIEW: 5 * 60_000,
  VERIFY_DRAFT_DRAFT: 60_000,
} as const

export const IDEMPOTENCY_RETENTION_MS = 24 * 60 * 60_000
export const IDEMPOTENCY_MAX_RESPONSE_BYTES = 16 * 1024

export const CIRCUIT_BREAKER = {
  FAILURES_TO_OPEN: 5,
  WINDOW_MS: 2 * 60_000,
  OPEN_MS: 60_000,
  HALF_OPEN_SUCCESSES_TO_CLOSE: 2,
} as const

