// Single source of truth for the app's icon library.
// Preset: Remix icons (Radix Maia / Neutral / Amber / LTR).
//
// All app code should import icons from here, never directly from icon packages,
// so we can swap libraries without touching the whole codebase.

import {
  RiAddLine,
  RiArrowDownLine,
  RiArrowDownSLine,
  RiArrowLeftLine,
  RiArrowLeftSLine,
  RiArrowRightLine,
  RiArrowRightSLine,
  RiArrowRightUpLine,
  RiArrowUpLine,
  RiArrowUpSLine,
  RiBarChartLine,
  RiBellLine,
  RiCheckboxBlankCircleLine,
  RiCheckboxCircleLine,
  RiCheckLine,
  RiCloseLine,
  RiComputerLine,
  RiDashboardLine,
  RiDeleteBinLine,
  RiEditLine,
  RiErrorWarningLine,
  RiExternalLinkLine,
  RiEyeLine,
  RiFileCopyLine,
  RiFilter3Line,
  RiFlashlightLine,
  RiGlobalLine,
  RiHistoryLine,
  RiInboxLine,
  RiLineChartLine,
  RiLoader4Line,
  RiLogoutBoxRLine,
  RiMailLine,
  RiMailOpenLine,
  RiMapPinLine,
  RiMenuLine,
  RiMessage2Line,
  RiMoonLine,
  RiMoreLine,
  RiPencilLine,
  RiQuestionLine,
  RiRefreshLine,
  RiSaveLine,
  RiSearchLine,
  RiSendPlaneLine,
  RiSettings3Line,
  RiShieldCheckLine,
  RiSparklingLine,
  RiStarFill,
  RiStarLine,
  RiSunLine,
  RiTeamLine,
  RiThumbDownLine,
  RiThumbUpLine,
  RiTimeLine,
  RiUserLine,
} from "@remixicon/react"

export {
  RiArrowLeftLine as ArrowLeft,
  RiExternalLinkLine as ExternalLink,
  RiRefreshLine as RefreshCw,
  RiBellLine as Bell,
  RiArrowDownSLine as ChevronDown,
  RiArrowRightSLine as ChevronRight,
  RiArrowUpSLine as ChevronUp,
  RiCheckLine as Check,
  RiCheckboxCircleLine as CheckCircle2,
  RiCheckboxBlankCircleLine as Circle,
  RiLoader4Line as Loader2,
  RiTimeLine as Clock,
  RiFileCopyLine as Copy,
  RiMailLine as Mail,
  RiSaveLine as Save,
  RiSettings3Line as Settings,
  RiComputerLine as Laptop,
  RiFlashlightLine as Zap,
  RiMenuLine as Menu,
  RiSearchLine as Search,
  RiMapPinLine as MapPin,
  RiMessage2Line as MessageSquare,
  RiMoonLine as Moon,
  RiAddLine as Plus,
  RiQuestionLine as CircleHelp,
  RiQuestionLine as HelpCircle,
  RiShieldCheckLine as ShieldCheck,
  RiLogoutBoxRLine as LogOut,
  RiSparklingLine as Sparkles,
  RiStarFill as StarFilled,
  RiStarLine as Star,
  RiSunLine as Sun,
  RiLineChartLine as TrendingUp,
  RiUserLine as User,
  RiTeamLine as Users,
  RiErrorWarningLine as AlertTriangle,
  RiCloseLine as X,
  RiDeleteBinLine as Trash2,
  RiArrowRightUpLine as ArrowUpRight,
  RiThumbUpLine as ThumbsUp,
  RiThumbDownLine as ThumbsDown,
  RiHistoryLine as History,
  RiBarChartLine as BarChart,
  RiEyeLine as Eye,
  RiPencilLine as Pencil,
  RiFilter3Line as Filter,
  RiArrowRightLine as ArrowRight,
  RiArrowLeftSLine as ChevronLeft,
  RiMoreLine as MoreHorizontal,
  RiDashboardLine as LayoutDashboard,
  RiMailOpenLine as Envelope,
  RiEditLine as Edit,
  RiSendPlaneLine as Send,
  RiGlobalLine as Globe,
  RiArrowUpLine as ArrowUp,
  RiArrowDownLine as ArrowDown,
  RiInboxLine as InboxIcon,
}
