// Single source of truth for the app's icon library.
// Preset: Phosphor icons (Nova / Zinc / Blue / LTR).
//
// All app code should import icons from here, never directly from icon packages,
// so we can swap libraries without touching the whole codebase.

export {
  ArrowLeft,
  ArrowSquareOut as ExternalLink,
  ArrowClockwise as RefreshCw,
  Bell,
  CaretDown as ChevronDown,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  Check,
  CheckCircle as CheckCircle2,
  Circle,
  CircleNotch as Loader2,
  Clock,
  Copy,
  EnvelopeSimple as Mail,
  FloppyDisk as Save,
  GearSix as Settings,
  Laptop,
  Lightning as Zap,
  List as Menu,
  MagnifyingGlass as Search,
  MapPin,
  ChatCenteredDots as MessageSquare,
  Moon,
  Plus,
  Question as CircleHelp,
  Question as HelpCircle,
  ShieldCheck,
  SignOut as LogOut,
  Sparkle as Sparkles,
  Star,
  Sun,
  TrendUp as TrendingUp,
  User,
  Users,
  Warning as AlertTriangle,
  X,
  Trash as Trash2,
  ArrowUpRight,
  ThumbsUp,
  ThumbsDown,
  ClockCounterClockwise as History,
  ChartBar as BarChart,
  Eye,
  PencilSimple as Pencil,
  FunnelSimple as Filter,
  ArrowRight,
  CaretLeft as ChevronLeft,
  DotsThree as MoreHorizontal,
  SquaresFour as LayoutDashboard,
  Envelope,
  PencilSimpleLine as Edit,
  PaperPlaneRight as Send,
  GlobeSimple as Globe,
  ArrowUp,
  ArrowDown,
  Tray as InboxIcon,
} from "@phosphor-icons/react/ssr"
